[bot]
driver = "~fastapi"
adapters = [
    "~onebot.v11",
]
superusers = ['1614591760','1023443249']
nickname = ['珂朵莉','Chtholly']

[plugin]
plugins = []
plugin_dirs=['plugins']

[Database]
database = 'Chtholly'

[image]
withdraw = true
last_time = 90