[project]
name = "Chtholly"
version = "0.1.0"
description = "Chtholly"
readme = "README.md"
authors = [{ name = "FrostN_0v0", email = "suny25802@gmail.com" }]
license = { text = "AGPL-3.0" }
requires-python = ">=3.14, <4.0"
dependencies = [
    "langid>=1.1.6",
    "nonebot-plugin-alconna>=0.62.0",
    "nonebot-plugin-uninfo>=0.11.0",
    "nonebot2>=2.4.0",
    "pydub>=0.25.1",
    "rich>=13.9.4",
    "ruamel-yaml>=0.18.17",
    "ujson>=5.10.0",
]

[tool.uv]
override-dependencies = [
    "httpx[http2]==0.27.2",
    "pillow>=11.0.0",
    "pypinyin>=0.54.0",
    "nonebot-plugin-htmlrender>=0.7.0a3"
]

[tool.uv.sources]
nonebot-plugin-wakatime = { git = "https://github.com/FrostN0v0/nonebot-plugin-wakatime", branch = "feat/ai-coding-render"}

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" },
    { name = "Telegram", module_name = "nonebot.adapters.telegram" },
    # {name = "nonebot-adapter-milky", module_name = "nonebot.adapters.milky"}
]
plugins = [
    "nonebot_plugin_memes_api",
    "nonebot_plugin_color_see_see",
    "nonebot_plugin_kawaii_status",
    "nonebot_plugin_pcr_sign",
    "nonebot_plugin_miao",
    "nonebot_bison",
    "nonebot_plugin_deepseek",
    "nonebot_plugin_skland",
    "nonebot_plugin_rollpig",
    "nonebot_plugin_doroending"
]
plugin_dirs = ["./plugins"]
builtin_plugins = []


[project.optional-dependencies]
adapters = [
    "nonebot-adapter-milky>=1.1.0",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot-adapter-qq>=1.5.3",
    "nonebot-adapter-telegram>=0.1.0b20",
]
test = [
    "nonebot2[aiohttp,fastapi,httpx,websockets]>=2.4.0",
    "nonebot-plugin-orm[default]>=0.7.6",
]
plugins = [
    "nonebot-bison>=0.9.14",
    "nonebot-plugin-rollpig>=0.2.5",
    "nonebot-plugin-memes-api>=0.5.1",
    "nonebot-plugin-beauty-rater>=0.1.3",
    "nonebot-plugin-color-see-see>=0.2.0",
    "nonebot-plugin-kawaii-status>=0.1.9",
    "nonebot-plugin-miao>=1.1.0",
    "nonebot-plugin-pcr-sign>=0.3.1",
    "nonebot-plugin-wakatime>=0.3.0",
    "nonebot-plugin-skland>=0.6.9",
    "nonebot-plugin-deepseek[full]>=0.2.0",
    "nonebot-plugin-picmenu-next>=0.1.6",
    "nonebot-plugin-deltaforce-simulator>=1.0.0",
    "nonebot-plugin-doroending>=0.2.0",
]
mockingbird = [
    "torch>=1.10.0",
    "scipy>=1.8.0",
    "librosa>=0.9.0",
    "numpy>=1.21.0",
    "numba>=0.55.0",
    "pypinyin>=0.40.0",
    "webrtcvad>=2.0.0",
    "Unidecode>=1.3.0",
    "inflect>=5.6.0",
    "loguru>=0.6.0"
]

[tool.ruff.lint]
select = [
  "W",   # pycodestyle warnings
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "UP",  # pyupgrade
  "C4",  # flake8-comprehensions
  "T10", # flake8-debugger
  "T20", # flake8-print
  "PYI", # flake8-pyi
  "PT",  # flake8-pytest-style
  "Q",   # flake8-quotes
  "TC",  # flake8-type-checking
  "RUF", # Ruff-specific rules
  "I",   # isort
]
ignore = [
  "E402",   # module-import-not-at-top-of-file
  "RUF001", # ambiguous-unicode-character-string
  "RUF002", # ambiguous-unicode-character-docstring
  "RUF003", # ambiguous-unicode-character-comment
]

[tool.pyright]
pythonVersion = "3.14"
pythonPlatform = "All"
typeCheckingMode = "basic"
